version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql:/var/lib/mysql

  postgres:
    container_name: postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  mail:
    image: codions/mailcatcher
    container_name: mail
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"
    environment:
      VIRTUAL_HOST: mail.local
      VIRTUAL_PORT: 1080

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: --appendonly yes --requirepass redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    environment:
      REDIS_PORT: 6379

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        VIRTUAL_HOST: portainer.local
        VIRTUAL_PORT: 9000
    ports:
      - "9000:9000"
    expose:
      - "9000"

  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"

networks:
  default:
    external:
      name: nginx-proxy